#!/bin/bash

echo "Hello there! My name is $0"
read -p "What is your name: " name
if [ $name = "Uuviee" ]; then 
name = "Boss"
fi
echo "Nice to meet you $name"

echo "I am a helpful bot, I make people smile for a living."
read -p "What do you do? " q1
if [$q1 = "engineering" ]; then 
q1 = "boo"
fi
echo "Wow! I hear some good things about $q1"

echo "Its been a pleasure meeting you $name"
echo "Bye!"

